### PR TITLE
Add support for buildpack-installation as per https://devcenter.herok…

### PR DESCRIPTION
**Pull request by benbardin**
…u.com/articles/platform-api-reference#buildpack-installations

Not sure how to test this?

### CODE REVIEW

**Comment by benbardin** [comment]
Besides deploying a test case with deploy-api

**Comment by aleontiev** [comment]
:+1:

As there are no unit tests currently, its probably best to do an integration test: 
- create an instance of the Heroku3 client with the token to the master environment
- call `heroku3.apps()['some-app'].update_buildpacks(['https://github.com/some/buildpack.git'])`
- check to make sure the buildpack is set using the Heroku CLI `heroku buildpacks -a some-app` 
- add a comment with commands run

**Comment by benbardin** [comment]
Found a fixed a bug. Looks like it works now: ```
Benjamins-MacBook-Pro% heroku buildpacks -a master-secrets
master-secrets has no Buildpack URL set.

> > > import heroku3; h = heroku3.from_key('...');h.apps()['master-secrets'].update_buildpacks(['https://github.com/some/buildpack.git']);

Benjamins-MacBook-Pro% heroku buildpacks -a master-secrets
=== master-secrets Buildpack URL
https://github.com/some/buildpack.git

> > > import heroku3; h = heroku3.from_key('...');h.apps()['master-secrets'].update_buildpacks([]);

Benjamins-MacBook-Pro% heroku buildpacks -a master-secrets
master-secrets has no Buildpack URL set.

```
```

**Comment by aleontiev** [comment]
:+1: nice work

**Pull request merged**
